import json
from pathlib import Path

def get_ans(index):
    return chr(ord('a') + index)

quizzes = {
    'assets/javascript_dom_basics_quiz.json': [
        {"que": "What does DOM stand for?", "options": ["Document Object Model", "Document Object Method", "Data Object Model", "Document Oriented Model"], "ans": get_ans(0)},
        {"que": "How to select element by ID?", "options": ["getElementById()", "getElementByClass()", "querySelector()", "getElementsByTagName()"], "ans": get_ans(0)},
        {"que": "What does querySelector() return?", "options": ["First matching element", "All matching elements", "Element array", "Node list"], "ans": get_ans(0)},
        {"que": "How to change element text?", "options": ["element.textContent = 'text'", "element.innerHTML = 'text'", "element.value = 'text'", "element.text = 'text'"], "ans": get_ans(0)},
        {"que": "What is innerHTML?", "options": ["HTML content as string", "Text content", "Element value", "Attribute value"], "ans": get_ans(0)},
        {"que": "How to add event listener?", "options": ["addEventListener()", "onEvent()", "listenEvent()", "attachEvent()"], "ans": get_ans(0)},
        {"que": "What does createElement() do?", "options": ["Creates new element", "Selects element", "Removes element", "Updates element"], "ans": get_ans(0)},
        {"que": "How to append child?", "options": ["appendChild()", "addChild()", "insertChild()", "pushChild()"], "ans": get_ans(0)},
        {"que": "What is document.body?", "options": ["Body element", "Head element", "HTML element", "Document root"], "ans": get_ans(0)},
        {"que": "How to get element by class?", "options": ["getElementsByClassName()", "getElementByClass()", "querySelectorAll('.class')", "getClassElements()"], "ans": get_ans(0)}
    ],
    'assets/javascript_events_quiz.json': [
        {"que": "What is an event?", "options": ["Action that occurs", "Function call", "Variable", "Object"], "ans": get_ans(0)},
        {"que": "How to handle click event?", "options": ["addEventListener('click', handler)", "onClick = handler", "click(handler)", "handleClick(handler)"], "ans": get_ans(0)},
        {"que": "What is event.target?", "options": ["Element that triggered event", "Event type", "Event handler", "Parent element"], "ans": get_ans(0)},
        {"que": "What does preventDefault() do?", "options": ["Stops default action", "Stops event bubbling", "Removes handler", "Adds handler"], "ans": get_ans(0)},
        {"que": "What is event bubbling?", "options": ["Event propagates up", "Event propagates down", "Event stops", "Event repeats"], "ans": get_ans(0)},
        {"que": "How to stop propagation?", "options": ["stopPropagation()", "preventDefault()", "stopEvent()", "cancelEvent()"], "ans": get_ans(0)},
        {"que": "What is event delegation?", "options": ["Handle events on parent", "Handle on child", "Handle on document", "Handle on window"], "ans": get_ans(0)},
        {"que": "What is keydown event?", "options": ["Key pressed down", "Key released", "Key pressed", "Key typed"], "ans": get_ans(0)},
        {"que": "What is submit event?", "options": ["Form submission", "Button click", "Input change", "Page load"], "ans": get_ans(0)},
        {"que": "How to remove event listener?", "options": ["removeEventListener()", "off()", "detachEvent()", "unlisten()"], "ans": get_ans(0)}
    ],
    'assets/javascript_fetch_basics_quiz.json': [
        {"que": "What does fetch() do?", "options": ["Makes HTTP request", "Parses JSON", "Creates promise", "Handles error"], "ans": get_ans(0)},
        {"que": "What does fetch() return?", "options": ["Promise", "Response object", "JSON data", "String"], "ans": get_ans(0)},
        {"que": "How to get JSON from response?", "options": ["response.json()", "response.text()", "response.data()", "response.parse()"], "ans": get_ans(0)},
        {"que": "What is response.ok?", "options": ["True if status 200-299", "True if success", "True if JSON", "True if text"], "ans": get_ans(0)},
        {"que": "How to handle fetch error?", "options": ["Check response.ok or catch", "Try/catch only", "If/else", "Switch"], "ans": get_ans(0)},
        {"que": "What is async function?", "options": ["Function that returns promise", "Synchronous function", "Callback function", "Event handler"], "ans": get_ans(0)},
        {"que": "What does await do?", "options": ["Waits for promise", "Calls function", "Returns value", "Throws error"], "ans": get_ans(0)},
        {"que": "What is try/catch for?", "options": ["Handle errors", "Loop code", "Conditional code", "Function code"], "ans": get_ans(0)},
        {"que": "What is finally block?", "options": ["Runs always", "Runs on success", "Runs on error", "Runs first"], "ans": get_ans(0)},
        {"que": "How to fetch with POST?", "options": ["fetch(url, {method: 'POST'})", "fetch(url, 'POST')", "post(url)", "send(url, 'POST')"], "ans": get_ans(0)}
    ],
    'assets/javascript_functions_quiz.json': [
        {"que": "How to declare function?", "options": ["function name() {}", "func name() {}", "def name() {}", "declare name() {}"], "ans": get_ans(0)},
        {"que": "What is function expression?", "options": ["const f = function() {}", "function f() {}", "f = function() {}", "var f = function() {}"], "ans": get_ans(0)},
        {"que": "What does return do?", "options": ["Returns value from function", "Exits function", "Continues function", "Restarts function"], "ans": get_ans(0)},
        {"que": "What are parameters?", "options": ["Input values", "Output values", "Local variables", "Global variables"], "ans": get_ans(0)},
        {"que": "What is scope?", "options": ["Variable accessibility", "Function size", "Code length", "Execution time"], "ans": get_ans(0)},
        {"que": "What is arrow function?", "options": ["() => {}", "function() {}", "=> {}", "() -> {}"], "ans": get_ans(0)},
        {"que": "What is callback?", "options": ["Function passed as argument", "Function returned", "Function called", "Function defined"], "ans": get_ans(0)},
        {"que": "What is higher-order function?", "options": ["Takes or returns function", "Simple function", "Built-in function", "Anonymous function"], "ans": get_ans(0)},
        {"que": "What is recursion?", "options": ["Function calls itself", "Function calls other", "Function loops", "Function returns"], "ans": get_ans(0)},
        {"que": "What is IIFE?", "options": ["Immediately Invoked Function Expression", "Instant Function Execution", "Inline Function Expression", "Internal Function Expression"], "ans": get_ans(0)}
    ],
    'assets/javascript_intro_quiz.json': [
        {"que": "What is JavaScript?", "options": ["Programming language for web", "Markup language", "Styling language", "Database language"], "ans": get_ans(0)},
        {"que": "Where does JS run?", "options": ["Browser and server", "Only browser", "Only server", "Desktop"], "ans": get_ans(0)},
        {"que": "How to include JS?", "options": ["<script>", "<js>", "<javascript>", "<code>"], "ans": get_ans(0)},
        {"que": "What is console.log?", "options": ["Prints to console", "Prints to page", "Alerts user", "Logs error"], "ans": get_ans(0)},
        {"que": "What is variable?", "options": ["Stores value", "Executes code", "Defines function", "Creates object"], "ans": get_ans(0)},
        {"que": "What is const?", "options": ["Constant variable", "Variable", "Function", "Object"], "ans": get_ans(0)},
        {"que": "What is let?", "options": ["Block-scoped variable", "Global variable", "Constant", "Function"], "ans": get_ans(0)},
        {"que": "What is if statement?", "options": ["Conditional execution", "Loop", "Function", "Variable"], "ans": get_ans(0)},
        {"que": "What is array?", "options": ["List of values", "Single value", "Object", "Function"], "ans": get_ans(0)},
        {"que": "What is object?", "options": ["Key-value collection", "List", "Value", "Function"], "ans": get_ans(0)}
    ],
    'assets/javascript_variables_quiz.json': [
        {"que": "What is var?", "options": ["Function-scoped variable", "Block-scoped", "Constant", "Global"], "ans": get_ans(0)},
        {"que": "What is let?", "options": ["Block-scoped variable", "Function-scoped", "Constant", "Global"], "ans": get_ans(0)},
        {"que": "What is const?", "options": ["Constant value", "Variable", "Function", "Object"], "ans": get_ans(0)},
        {"que": "What is hoisting?", "options": ["Declarations moved up", "Values moved up", "Code executed", "Variables deleted"], "ans": get_ans(0)},
        {"que": "What is temporal dead zone?", "options": ["Time before declaration", "After declaration", "During execution", "After execution"], "ans": get_ans(0)},
        {"que": "What is undefined?", "options": ["Unassigned value", "Null value", "Error", "Zero"], "ans": get_ans(0)},
        {"que": "What is null?", "options": ["Intentional absence", "Unassigned", "Error", "Empty string"], "ans": get_ans(0)},
        {"que": "What is scope?", "options": ["Variable visibility", "Code block", "Function", "File"], "ans": get_ans(0)},
        {"que": "What is global scope?", "options": ["Accessible everywhere", "Inside function", "Inside block", "Nowhere"], "ans": get_ans(0)},
        {"que": "What is local scope?", "options": ["Inside function/block", "Global", "Everywhere", "Nowhere"], "ans": get_ans(0)}
    ],
    'assets/js_arrays_quiz.json': [
        {"que": "What is an array?", "options": ["Ordered list of values", "Unordered list", "Single value", "Object"], "ans": get_ans(0)},
        {"que": "How to create an array?", "options": ["[] or new Array()", "{}", "()", "<>"], "ans": get_ans(0)},
        {"que": "What is array index?", "options": ["Position starting from 0", "Position starting from 1", "Name", "Value"], "ans": get_ans(0)},
        {"que": "Which method adds to end?", "options": ["push()", "add()", "append()", "insert()"], "ans": get_ans(0)},
        {"que": "Which method removes from end?", "options": ["pop()", "remove()", "delete()", "shift()"], "ans": get_ans(0)},
        {"que": "What does length property give?", "options": ["Number of elements", "Last index", "First element", "Type"], "ans": get_ans(0)},
        {"que": "What is forEach?", "options": ["Method to iterate", "Loop type", "Function", "Variable"], "ans": get_ans(0)},
        {"que": "What does map() return?", "options": ["New array with results", "Same array", "Single value", "Nothing"], "ans": get_ans(0)},
        {"que": "What does filter() do?", "options": ["Creates array with matching elements", "Removes elements", "Sorts elements", "Finds element"], "ans": get_ans(0)},
        {"que": "What does reduce() do?", "options": ["Reduces to single value", "Increases values", "Multiplies values", "Divides values"], "ans": get_ans(0)}
    ],
    'assets/js_arrow_quiz.json': [
        {"que": "What is arrow function?", "options": ["() => {}", "function() {}", "=> {}", "() -> {}"], "ans": get_ans(0)},
        {"que": "What is lexical this?", "options": ["Inherits from outer scope", "Own this", "Global this", "Undefined this"], "ans": get_ans(0)},
        {"que": "Can arrow functions be constructors?", "options": ["No", "Yes", "Sometimes", "Depends"], "ans": get_ans(0)},
        {"que": "What if single parameter?", "options": ["Can omit parentheses", "Must use parentheses", "Use brackets", "Use braces"], "ans": get_ans(0)},
        {"que": "What if single expression?", "options": ["Can omit braces and return", "Must use braces", "Must use return", "Use brackets"], "ans": get_ans(0)},
        {"que": "What is implicit return?", "options": ["No return keyword needed", "Must use return", "Optional return", "No return"], "ans": get_ans(0)},
        {"que": "Do arrow functions have arguments?", "options": ["No", "Yes", "Sometimes", "Depends"], "ans": get_ans(0)},
        {"que": "Can arrow functions be named?", "options": ["No, always anonymous", "Yes", "Sometimes", "Depends"], "ans": get_ans(0)},
        {"que": "What about super in arrow?", "options": ["Uses lexical super", "Own super", "No super", "Global super"], "ans": get_ans(0)},
        {"que": "When to use arrow functions?", "options": ["Callbacks, short functions", "Constructors, methods", "Global functions", "Event handlers"], "ans": get_ans(0)}
    ],
    'assets/js_async_quiz.json': [
        {"que": "What is async function?", "options": ["Returns promise", "Synchronous", "Callback", "Generator"], "ans": get_ans(0)},
        {"que": "What does await do?", "options": ["Waits for promise", "Calls function", "Returns value", "Throws error"], "ans": get_ans(0)},
        {"que": "What is promise?", "options": ["Future value", "Current value", "Error", "Function"], "ans": get_ans(0)},
        {"que": "What are promise states?", "options": ["pending, fulfilled, rejected", "running, done, error", "start, middle, end", "init, process, finish"], "ans": get_ans(0)},
        {"que": "What does then() do?", "options": ["Handles fulfillment", "Handles rejection", "Creates promise", "Resolves promise"], "ans": get_ans(0)},
        {"que": "What does catch() do?", "options": ["Handles rejection", "Handles fulfillment", "Creates promise", "Resolves promise"], "ans": get_ans(0)},
        {"que": "What does finally() do?", "options": ["Runs always", "Runs on success", "Runs on error", "Runs first"], "ans": get_ans(0)},
        {"que": "What is Promise.all?", "options": ["Waits for all", "Waits for first", "Rejects all", "Resolves all"], "ans": get_ans(0)},
        {"que": "What is Promise.race?", "options": ["Waits for first settle", "Waits for all", "Rejects first", "Resolves first"], "ans": get_ans(0)},
        {"que": "What is async/await?", "options": ["Syntactic sugar for promises", "New promise type", "Callback style", "Generator style"], "ans": get_ans(0)}
    ],
    'assets/js_closures_quiz.json': [
        {"que": "What is closure?", "options": ["Function with access to outer scope", "Closed function", "Local function", "Global function"], "ans": get_ans(0)},
        {"que": "What is lexical scope?", "options": ["Based on code structure", "Based on runtime", "Based on call", "Based on context"], "ans": get_ans(0)},
        {"que": "What does closure remember?", "options": ["Variables from outer scope", "Own variables", "Global variables", "Parameters"], "ans": get_ans(0)},
        {"que": "What is scope chain?", "options": ["Chain of scopes", "Chain of functions", "Chain of variables", "Chain of calls"], "ans": get_ans(0)},
        {"que": "What is private variable?", "options": ["Inaccessible from outside", "Accessible everywhere", "In function", "In block"], "ans": get_ans(0)},
        {"que": "How to create closure?", "options": ["Function inside function", "Function outside", "Global function", "Arrow function"], "ans": get_ans(0)},
        {"que": "What is module pattern?", "options": ["IIFE with return", "Function declaration", "Arrow function", "Callback"], "ans": get_ans(0)},
        {"que": "What is IIFE?", "options": ["Immediately Invoked Function Expression", "Instant Function", "Inline Function", "Internal Function"], "ans": get_ans(0)},
        {"que": "Why use closures?", "options": ["Encapsulation, data hiding", "Performance", "Syntax", "Compatibility"], "ans": get_ans(0)},
        {"que": "What is garbage collection?", "options": ["Automatic memory management", "Manual memory", "Memory allocation", "Memory deallocation"], "ans": get_ans(0)}
    ],
    'assets/js_conditions_quiz.json': [
        {"que": "What is if statement?", "options": ["Conditional execution", "Loop", "Function", "Variable"], "ans": get_ans(0)},
        {"que": "What is else?", "options": ["Alternative branch", "Same as if", "Loop", "Function"], "ans": get_ans(0)},
        {"que": "What is else if?", "options": ["Additional condition", "Nested if", "Loop", "Function"], "ans": get_ans(0)},
        {"que": "What is switch?", "options": ["Multiple conditions", "Single condition", "Loop", "Function"], "ans": get_ans(0)},
        {"que": "What is case in switch?", "options": ["Value to match", "Condition", "Variable", "Function"], "ans": get_ans(0)},
        {"que": "What is default in switch?", "options": ["Fallback case", "First case", "Last case", "Error case"], "ans": get_ans(0)},
        {"que": "What is ternary operator?", "options": ["condition ? true : false", "condition ? false : true", "true ? condition : false", "false ? condition : true"], "ans": get_ans(0)},
        {"que": "What are truthy values?", "options": ["Values considered true", "Always true", "Always false", "Undefined"], "ans": get_ans(0)},
        {"que": "What are falsy values?", "options": ["Values considered false", "Always false", "Always true", "Defined"], "ans": get_ans(0)},
        {"que": "What is short-circuiting?", "options": ["&& and || evaluation", "Fast evaluation", "Skip evaluation", "Reverse evaluation"], "ans": get_ans(0)}
    ],
    'assets/js_datatypes_quiz.json': [
        {"que": "What are primitive types?", "options": ["string, number, boolean, etc.", "object, array", "function, class", "null, undefined"], "ans": get_ans(0)},
        {"que": "What is typeof?", "options": ["Returns type string", "Returns value", "Returns object", "Returns array"], "ans": get_ans(0)},
        {"que": "What is string?", "options": ["Text data", "Number data", "Boolean data", "Object data"], "ans": get_ans(0)},
        {"que": "What is number?", "options": ["Numeric data", "Text data", "Boolean data", "Object data"], "ans": get_ans(0)},
        {"que": "What is boolean?", "options": ["true or false", "Text", "Number", "Object"], "ans": get_ans(0)},
        {"que": "What is undefined?", "options": ["Unassigned value", "Null value", "Error", "Zero"], "ans": get_ans(0)},
        {"que": "What is null?", "options": ["Intentional absence", "Unassigned", "Error", "Empty string"], "ans": get_ans(0)},
        {"que": "What is symbol?", "options": ["Unique identifier", "String", "Number", "Object"], "ans": get_ans(0)},
        {"que": "What is BigInt?", "options": ["Large integer", "Small number", "Float", "String"], "ans": get_ans(0)},
        {"que": "What is object?", "options": ["Reference type", "Primitive type", "Function", "Array"], "ans": get_ans(0)}
    ],
    'assets/js_debounce_quiz.json': [
        {"que": "What is debouncing?", "options": ["Delays execution until inactivity", "Executes immediately", "Executes repeatedly", "Stops execution"], "ans": get_ans(0)},
        {"que": "What is throttling?", "options": ["Limits execution rate", "Delays execution", "Stops execution", "Repeats execution"], "ans": get_ans(0)},
        {"que": "When to use debounce?", "options": ["Input events like search", "Scroll events", "Click events", "Load events"], "ans": get_ans(0)},
        {"que": "When to use throttle?", "options": ["Scroll, resize events", "Input events", "Click events", "Load events"], "ans": get_ans(0)},
        {"que": "What is setTimeout?", "options": ["Schedules function call", "Calls immediately", "Cancels call", "Repeats call"], "ans": get_ans(0)},
        {"que": "What is clearTimeout?", "options": ["Cancels scheduled call", "Schedules call", "Calls immediately", "Repeats call"], "ans": get_ans(0)},
        {"que": "How to implement debounce?", "options": ["Clear and set timeout", "Set timeout only", "Clear only", "No timeout"], "ans": get_ans(0)},
        {"que": "What is leading edge?", "options": ["Execute at start", "Execute at end", "Execute in middle", "Don't execute"], "ans": get_ans(0)},
        {"que": "What is trailing edge?", "options": ["Execute at end", "Execute at start", "Execute in middle", "Don't execute"], "ans": get_ans(0)},
        {"que": "Why use debounce/throttle?", "options": ["Performance optimization", "Code size", "Syntax", "Compatibility"], "ans": get_ans(0)}
    ],
    'assets/js_destructuring_quiz.json': [
        {"que": "What is destructuring?", "options": ["Extract values from arrays/objects", "Create arrays/objects", "Delete values", "Sort values"], "ans": get_ans(0)},
        {"que": "How to destructure array?", "options": ["const [a, b] = array", "const {a, b} = array", "const a, b = array", "const array = [a, b]"], "ans": get_ans(0)},
        {"que": "How to destructure object?", "options": ["const {a, b} = object", "const [a, b] = object", "const a, b = object", "const object = {a, b}"], "ans": get_ans(0)},
        {"que": "What is default value?", "options": ["Value if undefined", "Initial value", "Final value", "Null value"], "ans": get_ans(0)},
        {"que": "What is rest in destructuring?", "options": ["Remaining values", "First values", "All values", "No values"], "ans": get_ans(0)},
        {"que": "Can rename in object destructuring?", "options": ["Yes, with colon", "No", "With equals", "With comma"], "ans": get_ans(0)},
        {"que": "What is nested destructuring?", "options": ["Destructure nested structures", "Simple destructuring", "Array only", "Object only"], "ans": get_ans(0)},
        {"que": "What is parameter destructuring?", "options": ["Destructure in function params", "Destructure in return", "Destructure in loop", "Destructure in if"], "ans": get_ans(0)},
        {"que": "What happens if no match?", "options": ["Undefined", "Error", "Null", "Empty"], "ans": get_ans(0)},
        {"que": "Why use destructuring?", "options": ["Cleaner code", "Performance", "Memory", "Security"], "ans": get_ans(0)}
    ],
    'assets/js_dom_quiz.json': [
        {"que": "What is DOM?", "options": ["Document Object Model", "Document Object Method", "Data Object Model", "Document Oriented Model"], "ans": get_ans(0)},
        {"que": "How to select by ID?", "options": ["getElementById()", "getElementByClass()", "querySelector()", "getElementsByTagName()"], "ans": get_ans(0)},
        {"que": "What does querySelector() return?", "options": ["First element", "All elements", "Array", "List"], "ans": get_ans(0)},
        {"que": "How to change text?", "options": ["textContent", "innerHTML", "value", "attribute"], "ans": get_ans(0)},
        {"que": "What is innerHTML?", "options": ["HTML string", "Text string", "Value", "Attribute"], "ans": get_ans(0)},
        {"que": "How to add event?", "options": ["addEventListener()", "onEvent()", "listen()", "attach()"], "ans": get_ans(0)},
        {"que": "What does createElement() do?", "options": ["Creates element", "Selects element", "Removes element", "Updates element"], "ans": get_ans(0)},
        {"que": "How to append?", "options": ["appendChild()", "addChild()", "insert()", "push()"], "ans": get_ans(0)},
        {"que": "What is classList?", "options": ["Manage classes", "List elements", "List attributes", "List children"], "ans": get_ans(0)},
        {"que": "How to remove element?", "options": ["remove()", "delete()", "erase()", "clear()"], "ans": get_ans(0)}
    ],
    'assets/js_error_quiz.json': [
        {"que": "What is try?", "options": ["Block to test", "Block for error", "Block for success", "Block for catch"], "ans": get_ans(0)},
        {"que": "What is catch?", "options": ["Block for errors", "Block for success", "Block for test", "Block for finally"], "ans": get_ans(0)},
        {"que": "What is finally?", "options": ["Block that always runs", "Block for errors", "Block for success", "Block for test"], "ans": get_ans(0)},
        {"que": "What is throw?", "options": ["Throws error", "Catches error", "Handles error", "Ignores error"], "ans": get_ans(0)},
        {"que": "What is Error object?", "options": ["Has message and name", "Has code", "Has stack", "All of above"], "ans": get_ans(3)},
        {"que": "What is ReferenceError?", "options": ["Undefined variable", "Type error", "Syntax error", "Range error"], "ans": get_ans(0)},
        {"que": "What is TypeError?", "options": ["Wrong type operation", "Undefined variable", "Syntax error", "Range error"], "ans": get_ans(0)},
        {"que": "What is SyntaxError?", "options": ["Invalid syntax", "Wrong type", "Undefined", "Range"], "ans": get_ans(0)},
        {"que": "How to create custom error?", "options": ["new Error('message')", "throw 'message'", "Error('message')", "catch 'message'"], "ans": get_ans(0)},
        {"que": "Why handle errors?", "options": ["Graceful failure", "Debugging", "User experience", "All of above"], "ans": get_ans(3)}
    ],
    'assets/js_es6_quiz.json': [
        {"que": "What is ES6?", "options": ["ECMAScript 2015", "ECMAScript 6", "JavaScript 6", "Modern JS"], "ans": get_ans(0)},
        {"que": "What is let?", "options": ["Block-scoped variable", "Function-scoped", "Global", "Constant"], "ans": get_ans(0)},
        {"que": "What is const?", "options": ["Block-scoped constant", "Variable", "Function", "Global"], "ans": get_ans(0)},
        {"que": "What is arrow function?", "options": ["() => {}", "function() {}", "=> {}", "() -> {}"], "ans": get_ans(0)},
        {"que": "What is template literal?", "options": ["`string ${var}`", "'string' + var", "\"string\" + var", "string + var"], "ans": get_ans(0)},
        {"que": "What is destructuring?", "options": ["Extract values", "Create values", "Delete values", "Sort values"], "ans": get_ans(0)},
        {"que": "What is spread operator?", "options": ["...array", "...object", "..array", "..object"], "ans": get_ans(0)},
        {"que": "What is rest parameter?", "options": ["...args", "...params", "..args", "..params"], "ans": get_ans(0)},
        {"que": "What is class?", "options": ["Blueprint for objects", "Object", "Function", "Variable"], "ans": get_ans(0)},
        {"que": "What is module?", "options": ["Reusable code file", "Function", "Class", "Variable"], "ans": get_ans(0)}
    ],
    'assets/js_event_loop_quiz.json': [
        {"que": "What is event loop?", "options": ["Handles async operations", "Handles sync operations", "Handles loops", "Handles events"], "ans": get_ans(0)},
        {"que": "What is call stack?", "options": ["Execution stack", "Event queue", "Microtask queue", "Callback queue"], "ans": get_ans(0)},
        {"que": "What is task queue?", "options": ["Callback queue", "Call stack", "Microtask queue", "Event queue"], "ans": get_ans(0)},
        {"que": "What is microtask queue?", "options": ["Higher priority queue", "Lower priority", "Same as task", "For events"], "ans": get_ans(0)},
        {"que": "What executes first?", "options": ["Call stack", "Task queue", "Microtask queue", "Event loop"], "ans": get_ans(0)},
        {"que": "When does event loop run?", "options": ["After call stack empty", "Always", "On events", "On timers"], "ans": get_ans(0)},
        {"que": "What is setTimeout?", "options": ["Adds to task queue", "Adds to microtask", "Executes immediately", "Blocks"], "ans": get_ans(0)},
        {"que": "What is Promise.then?", "options": ["Adds to microtask queue", "Adds to task queue", "Executes immediately", "Blocks"], "ans": get_ans(0)},
        {"que": "Why understand event loop?", "options": ["Predict execution order", "Write better code", "Debug async", "All of above"], "ans": get_ans(3)},
        {"que": "What is blocking?", "options": ["Long sync operation", "Async operation", "Short operation", "Event operation"], "ans": get_ans(0)}
    ],
    'assets/js_events_quiz.json': [
        {"que": "What is event?", "options": ["User action or occurrence", "Function", "Variable", "Object"], "ans": get_ans(0)},
        {"que": "How to add listener?", "options": ["addEventListener()", "onEvent()", "listen()", "attach()"], "ans": get_ans(0)},
        {"que": "What is event object?", "options": ["Contains event info", "Event handler", "Event type", "Event target"], "ans": get_ans(0)},
        {"que": "What is event.target?", "options": ["Element that triggered", "Event type", "Handler", "Parent"], "ans": get_ans(0)},
        {"que": "What does preventDefault() do?", "options": ["Stops default action", "Stops bubbling", "Removes listener", "Adds listener"], "ans": get_ans(0)},
        {"que": "What is bubbling?", "options": ["Event propagates up", "Event propagates down", "Event stops", "Event repeats"], "ans": get_ans(0)},
        {"que": "How to stop bubbling?", "options": ["stopPropagation()", "preventDefault()", "stopEvent()", "cancel()"], "ans": get_ans(0)},
        {"que": "What is capturing?", "options": ["Event propagates down", "Event propagates up", "Event stops", "Event repeats"], "ans": get_ans(0)},
        {"que": "What is event delegation?", "options": ["Handle on parent", "Handle on child", "Handle on document", "Handle on window"], "ans": get_ans(0)},
        {"que": "How to remove listener?", "options": ["removeEventListener()", "off()", "detach()", "unlisten()"], "ans": get_ans(0)}
    ],
    'assets/js_fetch_quiz.json': [
        {"que": "What does fetch() do?", "options": ["Makes HTTP request", "Parses JSON", "Creates promise", "Handles error"], "ans": get_ans(0)},
        {"que": "What does fetch() return?", "options": ["Promise<Response>", "Response", "JSON", "String"], "ans": get_ans(0)},
        {"que": "How to get JSON?", "options": ["response.json()", "response.text()", "response.data()", "response.parse()"], "ans": get_ans(0)},
        {"que": "What is response.ok?", "options": ["True for 200-299", "True for success", "True for JSON", "True for text"], "ans": get_ans(0)},
        {"que": "How to handle error?", "options": ["Check response.ok or catch", "Try/catch only", "If/else", "Switch"], "ans": get_ans(0)},
        {"que": "What is async/await?", "options": ["Syntactic sugar", "New promise", "Callback", "Generator"], "ans": get_ans(0)},
        {"que": "Can await be top-level?", "options": ["In modules", "No", "Yes", "In functions"], "ans": get_ans(0)},
        {"que": "What is Promise.all?", "options": ["Wait for all", "Wait for first", "Reject all", "Resolve all"], "ans": get_ans(0)},
        {"que": "What is Promise.race?", "options": ["Wait for first settle", "Wait for all", "Reject first", "Resolve first"], "ans": get_ans(0)},
        {"que": "How to send POST?", "options": ["fetch(url, {method: 'POST'})", "fetch(url, 'POST')", "post(url)", "send(url, 'POST')"], "ans": get_ans(0)}
    ],
    'assets/js_functions_quiz.json': [
        {"que": "How to declare function?", "options": ["function name() {}", "func name() {}", "def name() {}", "declare name() {}"], "ans": get_ans(0)},
        {"que": "What is function expression?", "options": ["const f = function() {}", "function f() {}", "f = function() {}", "var f = function() {}"], "ans": get_ans(0)},
        {"que": "What does return do?", "options": ["Returns value", "Exits function", "Continues", "Restarts"], "ans": get_ans(0)},
        {"que": "What are parameters?", "options": ["Input values", "Output values", "Local vars", "Global vars"], "ans": get_ans(0)},
        {"que": "What is scope?", "options": ["Variable accessibility", "Function size", "Code length", "Time"], "ans": get_ans(0)},
        {"que": "What is arrow function?", "options": ["() => {}", "function() {}", "=> {}", "() -> {}"], "ans": get_ans(0)},
        {"que": "What is callback?", "options": ["Function as argument", "Function returned", "Function called", "Function defined"], "ans": get_ans(0)},
        {"que": "What is higher-order function?", "options": ["Takes/returns function", "Simple function", "Built-in", "Anonymous"], "ans": get_ans(0)},
        {"que": "What is recursion?", "options": ["Calls itself", "Calls other", "Loops", "Returns"], "ans": get_ans(0)},
        {"que": "What is IIFE?", "options": ["Immediately Invoked Function Expression", "Instant Function", "Inline Function", "Internal Function"], "ans": get_ans(0)}
    ],
    'assets/js_hoisting_quiz.json': [
        {"que": "What is hoisting?", "options": ["Declarations moved to top", "Values moved to top", "Code executed", "Variables deleted"], "ans": get_ans(0)},
        {"que": "What is hoisted?", "options": ["var, function declarations", "let, const", "Expressions", "Assignments"], "ans": get_ans(0)},
        {"que": "What is temporal dead zone?", "options": ["Before let/const declaration", "After declaration", "During execution", "After execution"], "ans": get_ans(0)},
        {"que": "What happens with var?", "options": ["Hoisted with undefined", "Hoisted with value", "Not hoisted", "Error"], "ans": get_ans(0)},
        {"que": "What happens with let?", "options": ["Hoisted but not initialized", "Hoisted with undefined", "Not hoisted", "Error"], "ans": get_ans(0)},
        {"que": "What happens with const?", "options": ["Hoisted but not initialized", "Hoisted with undefined", "Not hoisted", "Error"], "ans": get_ans(0)},
        {"que": "What about function declarations?", "options": ["Hoisted with definition", "Hoisted without", "Not hoisted", "Error"], "ans": get_ans(0)},
        {"que": "What about function expressions?", "options": ["Not hoisted", "Hoisted", "Depends", "Error"], "ans": get_ans(0)},
        {"que": "Why avoid hoisting reliance?", "options": ["Confusing code", "Better practices", "Modern JS", "All of above"], "ans": get_ans(3)},
        {"que": "What is strict mode?", "options": ["Prevents some errors", "Allows hoisting", "Disables hoisting", "Changes hoisting"], "ans": get_ans(0)}
    ],
    'assets/js_intro_quiz.json': [
        {"que": "What is JavaScript?", "options": ["Programming language for web", "Markup language", "Styling language", "Database language"], "ans": get_ans(0)},
        {"que": "Where does JS run?", "options": ["Browser and server", "Only browser", "Only server", "Desktop"], "ans": get_ans(0)},
        {"que": "How to include JS?", "options": ["<script>", "<js>", "<javascript>", "<code>"], "ans": get_ans(0)},
        {"que": "What is console.log?", "options": ["Prints to console", "Prints to page", "Alerts user", "Logs error"], "ans": get_ans(0)},
        {"que": "What is variable?", "options": ["Stores value", "Executes code", "Defines function", "Creates object"], "ans": get_ans(0)},
        {"que": "What is const?", "options": ["Constant variable", "Variable", "Function", "Object"], "ans": get_ans(0)},
        {"que": "What is let?", "options": ["Block-scoped variable", "Global variable", "Constant", "Function"], "ans": get_ans(0)},
        {"que": "What is if statement?", "options": ["Conditional execution", "Loop", "Function", "Variable"], "ans": get_ans(0)},
        {"que": "What is array?", "options": ["List of values", "Single value", "Object", "Function"], "ans": get_ans(0)},
        {"que": "What is object?", "options": ["Key-value collection", "List", "Value", "Function"], "ans": get_ans(0)}
    ],
    'assets/js_json_quiz.json': [
        {"que": "What does JSON stand for?", "options": ["JavaScript Object Notation", "Java Script Object Node", "Java Standard Object Notation", "JavaScript Standard Object Node"], "ans": get_ans(0)},
        {"que": "What is JSON?", "options": ["Data format", "Programming language", "Markup language", "Styling language"], "ans": get_ans(0)},
        {"que": "What does JSON.parse() do?", "options": ["Converts JSON string to object", "Converts object to string", "Validates JSON", "Formats JSON"], "ans": get_ans(0)},
        {"que": "What does JSON.stringify() do?", "options": ["Converts object to JSON string", "Converts string to object", "Validates JSON", "Formats JSON"], "ans": get_ans(0)},
        {"que": "What types does JSON support?", "options": ["object, array, string, number, boolean, null", "function, symbol, undefined", "date, regex", "all types"], "ans": get_ans(0)},
        {"que": "What happens to undefined?", "options": ["Omitted in stringify", "Becomes null", "Error", "String"], "ans": get_ans(0)},
        {"que": "What happens to function?", "options": ["Omitted in stringify", "Becomes null", "Error", "String"], "ans": get_ans(0)},
        {"que": "What is JSON schema?", "options": ["Describes JSON structure", "Validates JSON", "Parses JSON", "Stringifies JSON"], "ans": get_ans(0)},
        {"que": "Is JSON a subset of JS?", "options": ["Yes", "No", "Sometimes", "Depends"], "ans": get_ans(0)},
        {"que": "Why use JSON?", "options": ["Data interchange", "Storage", "API responses", "All of above"], "ans": get_ans(3)}
    ],
    'assets/js_local_storage_quiz.json': [
        {"que": "What is localStorage?", "options": ["Browser storage", "Server storage", "Memory storage", "File storage"], "ans": get_ans(0)},
        {"que": "How to store data?", "options": ["localStorage.setItem(key, value)", "localStorage[key] = value", "localStorage.add(key, value)", "localStorage.put(key, value)"], "ans": get_ans(0)},
        {"que": "How to get data?", "options": ["localStorage.getItem(key)", "localStorage[key]", "localStorage.get(key)", "localStorage.read(key)"], "ans": get_ans(0)},
        {"que": "How to remove data?", "options": ["localStorage.removeItem(key)", "delete localStorage[key]", "localStorage.delete(key)", "localStorage.clear(key)"], "ans": get_ans(0)},
        {"que": "How to clear all?", "options": ["localStorage.clear()", "localStorage.removeAll()", "localStorage.deleteAll()", "localStorage.empty()"], "ans": get_ans(0)},
        {"que": "What type are values?", "options": ["Strings", "Objects", "Numbers", "Booleans"], "ans": get_ans(0)},
        {"que": "How to store object?", "options": ["JSON.stringify()", "Object.toString()", "Object.stringify()", "JSON.parse()"], "ans": get_ans(0)},
        {"que": "How to retrieve object?", "options": ["JSON.parse()", "JSON.stringify()", "Object.parse()", "Object.fromString()"], "ans": get_ans(0)},
        {"que": "What is storage limit?", "options": ["5-10MB", "Unlimited", "1MB", "100MB"], "ans": get_ans(0)},
        {"que": "Does it persist?", "options": ["Yes, across sessions", "No, session only", "No, tab only", "No, page only"], "ans": get_ans(0)}
    ],
    'assets/js_loops_quiz.json': [
        {"que": "What is for loop?", "options": ["Repeats with counter", "Repeats while condition", "Repeats over array", "Repeats over object"], "ans": get_ans(0)},
        {"que": "What is while loop?", "options": ["Repeats while condition true", "Repeats with counter", "Repeats over array", "Repeats over object"], "ans": get_ans(0)},
        {"que": "What is do-while?", "options": ["Executes at least once", "May not execute", "For arrays", "For objects"], "ans": get_ans(0)},
        {"que": "What is for...of?", "options": ["Iterates over iterable", "Iterates with index", "Iterates over object", "Iterates while"], "ans": get_ans(0)},
        {"que": "What is for...in?", "options": ["Iterates over keys", "Iterates with index", "Iterates over array", "Iterates while"], "ans": get_ans(0)},
        {"que": "What is forEach?", "options": ["Array method to iterate", "Loop type", "Function", "Variable"], "ans": get_ans(0)},
        {"que": "What is break?", "options": ["Exits loop", "Continues loop", "Skips iteration", "Restarts loop"], "ans": get_ans(0)},
        {"que": "What is continue?", "options": ["Skips to next iteration", "Exits loop", "Restarts loop", "Stops loop"], "ans": get_ans(0)},
        {"que": "What is infinite loop?", "options": ["Never ends", "Ends after count", "Ends on condition", "Ends on break"], "ans": get_ans(0)},
        {"que": "Why use loops?", "options": ["Repeat actions", "Process data", "Automate tasks", "All of above"], "ans": get_ans(3)}
    ],
    'assets/js_memory_quiz.json': [
        {"que": "What is garbage collection?", "options": ["Automatic memory management", "Manual memory", "Memory allocation", "Memory deallocation"], "ans": get_ans(0)},
        {"que": "What is memory leak?", "options": ["Unreleased memory", "Released memory", "Allocated memory", "Used memory"], "ans": get_ans(0)},
        {"que": "What causes memory leaks?", "options": ["Unremoved references", "Removed references", "No references", "Weak references"], "ans": get_ans(0)},
        {"que": "What is reference?", "options": ["Pointer to object", "Object itself", "Memory address", "Variable name"], "ans": get_ans(0)},
        {"que": "What is heap?", "options": ["Dynamic memory", "Stack memory", "Code memory", "Static memory"], "ans": get_ans(0)},
        {"que": "What is stack?", "options": ["Function call memory", "Object memory", "Global memory", "Dynamic memory"], "ans": get_ans(0)},
        {"que": "What is closure memory?", "options": ["Retains outer variables", "Releases variables", "No variables", "Own variables"], "ans": get_ans(0)},
        {"que": "How to avoid leaks?", "options": ["Remove references", "Add references", "Use closures", "Use globals"], "ans": get_ans(0)},
        {"que": "What is WeakMap?", "options": ["Weak references", "Strong references", "No references", "Map references"], "ans": get_ans(0)},
        {"que": "Why care about memory?", "options": ["Performance and stability", "Code size", "Syntax", "Compatibility"], "ans": get_ans(0)}
    ],
    'assets/js_modules_quiz.json': [
        {"que": "What is module?", "options": ["Reusable code file", "Function", "Class", "Variable"], "ans": get_ans(0)},
        {"que": "How to export?", "options": ["export", "module.exports", "exports", "All of above"], "ans": get_ans(3)},
        {"que": "How to import?", "options": ["import", "require()", "load()", "include()"], "ans": get_ans(0)},
        {"que": "What is default export?", "options": ["Single main export", "Named export", "All exports", "No export"], "ans": get_ans(0)},
        {"que": "What is named export?", "options": ["Multiple exports", "Single export", "Default export", "No export"], "ans": get_ans(0)},
        {"que": "What is CommonJS?", "options": ["require/module.exports", "import/export", "AMD", "UMD"], "ans": get_ans(0)},
        {"que": "What is ES modules?", "options": ["import/export", "require/module.exports", "AMD", "UMD"], "ans": get_ans(0)},
        {"que": "What is tree shaking?", "options": ["Removes unused code", "Adds code", "Optimizes code", "Bundles code"], "ans": get_ans(0)},
        {"que": "What is bundler?", "options": ["Combines modules", "Splits modules", "Loads modules", "Exports modules"], "ans": get_ans(0)},
        {"que": "Why use modules?", "options": ["Organization and reuse", "Performance", "Compatibility", "All of above"], "ans": get_ans(3)}
    ],
    'assets/js_objects_quiz.json': [
        {"que": "What is object?", "options": ["Key-value collection", "List", "Value", "Function"], "ans": get_ans(0)},
        {"que": "How to create object?", "options": ["{}", "[]", "()", "<>"], "ans": get_ans(0)},
        {"que": "How to access property?", "options": ["object.key or object['key']", "object(key)", "object{key}", "object[key]"], "ans": get_ans(0)},
        {"que": "How to add property?", "options": ["object.newKey = value", "object.add(newKey, value)", "object.push(newKey, value)", "object.insert(newKey, value)"], "ans": get_ans(0)},
        {"que": "How to delete property?", "options": ["delete object.key", "object.remove(key)", "object.delete(key)", "object.erase(key)"], "ans": get_ans(0)},
        {"que": "What is method?", "options": ["Function property", "Value property", "Key property", "Object property"], "ans": get_ans(0)},
        {"que": "What is this?", "options": ["Current object", "Global object", "Parent object", "Child object"], "ans": get_ans(0)},
        {"que": "What is prototype?", "options": ["Shared properties", "Own properties", "Static properties", "Dynamic properties"], "ans": get_ans(0)},
        {"que": "What is Object.keys()?", "options": ["Array of keys", "Array of values", "Object", "String"], "ans": get_ans(0)},
        {"que": "What is JSON?", "options": ["Object notation", "Array notation", "Function notation", "Variable notation"], "ans": get_ans(0)}
    ],
    'assets/js_operators_quiz.json': [
        {"que": "What is arithmetic operator?", "options": ["+, -, *, /, %", "=, ==, ===", "&&, ||, !", "&, |, ^"], "ans": get_ans(0)},
        {"que": "What is assignment operator?", "options": ["=", "+=, -=", "*=, /=", "%="], "ans": get_ans(0)},
        {"que": "What is comparison operator?", "options": ["==, ===, !=, !==, <, >", "+, -, *, /", "&&, ||", "&, |"], "ans": get_ans(0)},
        {"que": "What is === vs ==", "options": ["Strict vs loose equality", "Assignment vs equality", "Arithmetic vs comparison", "Logical vs bitwise"], "ans": get_ans(0)},
        {"que": "What is logical operator?", "options": ["&&, ||, !", "+, -, *, /", "==, ===", "&, |"], "ans": get_ans(0)},
        {"que": "What is ternary operator?", "options": ["condition ? true : false", "condition ? false : true", "true ? condition : false", "false ? condition : true"], "ans": get_ans(0)},
        {"que": "What is bitwise operator?", "options": ["&, |, ^, ~, <<, >>", "+, -, *, /", "&&, ||", "==, ==="], "ans": get_ans(0)},
        {"que": "What is typeof?", "options": ["Type operator", "Arithmetic", "Comparison", "Logical"], "ans": get_ans(0)},
        {"que": "What is instanceof?", "options": ["Prototype check", "Type check", "Value check", "Equality check"], "ans": get_ans(0)},
        {"que": "What is operator precedence?", "options": ["Order of evaluation", "Order of execution", "Order of assignment", "Order of comparison"], "ans": get_ans(0)}
    ],
    'assets/js_promises_quiz.json': [
        {"que": "What is promise?", "options": ["Future value", "Current value", "Error", "Function"], "ans": get_ans(0)},
        {"que": "What are promise states?", "options": ["pending, fulfilled, rejected", "running, done, error", "start, middle, end", "init, process, finish"], "ans": get_ans(0)},
        {"que": "What does then() do?", "options": ["Handles fulfillment", "Handles rejection", "Creates promise", "Resolves promise"], "ans": get_ans(0)},
        {"que": "What does catch() do?", "options": ["Handles rejection", "Handles fulfillment", "Creates promise", "Resolves promise"], "ans": get_ans(0)},
        {"que": "What does finally() do?", "options": ["Runs always", "Runs on success", "Runs on error", "Runs first"], "ans": get_ans(0)},
        {"que": "How to create promise?", "options": ["new Promise()", "Promise()", "createPromise()", "makePromise()"], "ans": get_ans(0)},
        {"que": "What is Promise.resolve()?", "options": ["Creates resolved promise", "Creates rejected", "Creates pending", "Resolves existing"], "ans": get_ans(0)},
        {"que": "What is Promise.reject()?", "options": ["Creates rejected promise", "Creates resolved", "Creates pending", "Rejects existing"], "ans": get_ans(0)},
        {"que": "What is Promise.all?", "options": ["Waits for all", "Waits for first", "Rejects all", "Resolves all"], "ans": get_ans(0)},
        {"que": "What is Promise.race?", "options": ["Waits for first settle", "Waits for all", "Rejects first", "Resolves first"], "ans": get_ans(0)}
    ],
    'assets/js_prototypes_quiz.json': [
        {"que": "What is prototype?", "options": ["Shared object properties", "Own properties", "Static properties", "Dynamic properties"], "ans": get_ans(0)},
        {"que": "What is __proto__?", "options": ["Prototype reference", "Own property", "Static property", "Dynamic property"], "ans": get_ans(0)},
        {"que": "What is prototype chain?", "options": ["Chain of prototypes", "Chain of objects", "Chain of properties", "Chain of methods"], "ans": get_ans(0)},
        {"que": "How to add to prototype?", "options": ["Object.prototype.method = function", "object.method = function", "Object.method = function", "prototype.method = function"], "ans": get_ans(0)},
        {"que": "What is constructor?", "options": ["Function that creates object", "Object itself", "Prototype", "Method"], "ans": get_ans(0)},
        {"que": "What is instanceof?", "options": ["Checks prototype chain", "Checks type", "Checks value", "Checks property"], "ans": get_ans(0)},
        {"que": "What is Object.create()?", "options": ["Creates object with prototype", "Creates prototype", "Creates constructor", "Creates method"], "ans": get_ans(0)},
        {"que": "What is class?", "options": ["Syntactic sugar for prototype", "New inheritance", "Different from prototype", "Replaces prototype"], "ans": get_ans(0)},
        {"que": "Why use prototypes?", "options": ["Memory efficiency", "Code reuse", "Inheritance", "All of above"], "ans": get_ans(3)},
        {"que": "What is prototypal inheritance?", "options": ["Objects inherit from objects", "Classes inherit from classes", "Functions inherit", "Variables inherit"], "ans": get_ans(0)}
    ],
    'assets/js_scope_quiz.json': [
        {"que": "What is scope?", "options": ["Variable accessibility", "Code block", "Function", "File"], "ans": get_ans(0)},
        {"que": "What is global scope?", "options": ["Accessible everywhere", "Inside function", "Inside block", "Nowhere"], "ans": get_ans(0)},
        {"que": "What is function scope?", "options": ["Inside function", "Global", "Block", "Module"], "ans": get_ans(0)},
        {"que": "What is block scope?", "options": ["Inside {}", "Inside function", "Global", "Module"], "ans": get_ans(0)},
        {"que": "What is lexical scope?", "options": ["Based on code structure", "Based on runtime", "Based on call", "Based on context"], "ans": get_ans(0)},
        {"que": "What is closure?", "options": ["Function with outer scope access", "Closed function", "Local function", "Global function"], "ans": get_ans(0)},
        {"que": "What is var scope?", "options": ["Function scope", "Block scope", "Global scope", "Module scope"], "ans": get_ans(0)},
        {"que": "What is let scope?", "options": ["Block scope", "Function scope", "Global scope", "Module scope"], "ans": get_ans(0)},
        {"que": "What is const scope?", "options": ["Block scope", "Function scope", "Global scope", "Module scope"], "ans": get_ans(0)},
        {"que": "What is module scope?", "options": ["Inside module file", "Global", "Function", "Block"], "ans": get_ans(0)}
    ],
    'assets/js_session_storage_quiz.json': [
        {"que": "What is sessionStorage?", "options": ["Session-only storage", "Persistent storage", "Memory storage", "File storage"], "ans": get_ans(0)},
        {"que": "How to store data?", "options": ["sessionStorage.setItem(key, value)", "sessionStorage[key] = value", "sessionStorage.add(key, value)", "sessionStorage.put(key, value)"], "ans": get_ans(0)},
        {"que": "How to get data?", "options": ["sessionStorage.getItem(key)", "sessionStorage[key]", "sessionStorage.get(key)", "sessionStorage.read(key)"], "ans": get_ans(0)},
        {"que": "How to remove data?", "options": ["sessionStorage.removeItem(key)", "delete sessionStorage[key]", "sessionStorage.delete(key)", "sessionStorage.clear(key)"], "ans": get_ans(0)},
        {"que": "How to clear all?", "options": ["sessionStorage.clear()", "sessionStorage.removeAll()", "sessionStorage.deleteAll()", "sessionStorage.empty()"], "ans": get_ans(0)},
        {"que": "What type are values?", "options": ["Strings", "Objects", "Numbers", "Booleans"], "ans": get_ans(0)},
        {"que": "How to store object?", "options": ["JSON.stringify()", "Object.toString()", "Object.stringify()", "JSON.parse()"], "ans": get_ans(0)},
        {"que": "How to retrieve object?", "options": ["JSON.parse()", "JSON.stringify()", "Object.parse()", "Object.fromString()"], "ans": get_ans(0)},
        {"que": "What is storage limit?", "options": ["5-10MB", "Unlimited", "1MB", "100MB"], "ans": get_ans(0)},
        {"que": "Does it persist?", "options": ["No, session only", "Yes, across sessions", "No, tab only", "No, page only"], "ans": get_ans(0)}
    ],
    'assets/js_spread_quiz.json': [
        {"que": "What is spread operator?", "options": ["... expands iterable", "... packs iterable", ".. expands", ".. packs"], "ans": get_ans(0)},
        {"que": "How to spread array?", "options": ["[...array]", "[...array, newItem]", "[array...]", "[newItem, array...]"], "ans": get_ans(0)},
        {"que": "How to spread object?", "options": ["{...object}", "{...object, newProp: value}", "{object...}", "{newProp: value, object...}"], "ans": get_ans(0)},
        {"que": "What is rest parameter?", "options": ["... collects arguments", "... spreads arguments", ".. collects", ".. spreads"], "ans": get_ans(0)},
        {"que": "How to use rest in function?", "options": ["function f(...args)", "function f(...args) {}", "function f(args...)", "function f(args...) {}"], "ans": get_ans(0)},
        {"que": "What is shallow copy?", "options": ["Copies references", "Copies values", "Deep copy", "No copy"], "ans": get_ans(0)},
        {"que": "How to copy array?", "options": ["[...array]", "array.slice()", "Array.from(array)", "All of above"], "ans": get_ans(3)},
        {"que": "How to merge arrays?", "options": ["[...arr1, ...arr2]", "arr1.concat(arr2)", "arr1.push(...arr2)", "All of above"], "ans": get_ans(3)},
        {"que": "How to merge objects?", "options": ["{...obj1, ...obj2}", "Object.assign({}, obj1, obj2)", "obj1 + obj2", "obj1.merge(obj2)"], "ans": get_ans(0)},
        {"que": "When to use spread?", "options": ["Copy, merge, expand", "Pack, collect", "Sort, filter", "Map, reduce"], "ans": get_ans(0)}
    ],
    'assets/js_this_quiz.json': [
        {"que": "What is this?", "options": ["Current execution context", "Global object", "Function object", "Variable"], "ans": get_ans(0)},
        {"que": "What is this in global?", "options": ["window (non-strict)", "undefined (strict)", "global", "null"], "ans": get_ans(0)},
        {"que": "What is this in function?", "options": ["window (non-strict)", "undefined (strict)", "caller", "callee"], "ans": get_ans(0)},
        {"que": "What is this in method?", "options": ["Owning object", "Global", "Function", "Prototype"], "ans": get_ans(0)},
        {"que": "What is this in arrow?", "options": ["Lexical this", "Own this", "Global this", "Undefined"], "ans": get_ans(0)},
        {"que": "What is call()?", "options": ["Sets this and calls", "Calls function", "Sets this", "Binds this"], "ans": get_ans(0)},
        {"que": "What is apply()?", "options": ["Sets this and calls with array", "Calls function", "Sets this", "Binds this"], "ans": get_ans(0)},
        {"que": "What is bind()?", "options": ["Returns function with bound this", "Calls function", "Sets this", "Applies this"], "ans": get_ans(0)},
        {"que": "What is new?", "options": ["Creates object with this", "Calls function", "Sets this", "Binds this"], "ans": get_ans(0)},
        {"que": "Why understand this?", "options": ["Correct context", "Avoid bugs", "Better code", "All of above"], "ans": get_ans(3)}
    ],
    'assets/js_timers_quiz.json': [
        {"que": "What is setTimeout?", "options": ["Delays execution", "Repeats execution", "Stops execution", "Pauses execution"], "ans": get_ans(0)},
        {"que": "What is setInterval?", "options": ["Repeats execution", "Delays execution", "Stops execution", "Pauses execution"], "ans": get_ans(0)},
        {"que": "How to cancel setTimeout?", "options": ["clearTimeout(id)", "stopTimeout(id)", "cancelTimeout(id)", "endTimeout(id)"], "ans": get_ans(0)},
        {"que": "How to cancel setInterval?", "options": ["clearInterval(id)", "stopInterval(id)", "cancelInterval(id)", "endInterval(id)"], "ans": get_ans(0)},
        {"que": "What does setTimeout return?", "options": ["Timer ID", "Function", "Promise", "Undefined"], "ans": get_ans(0)},
        {"que": "What does setInterval return?", "options": ["Timer ID", "Function", "Promise", "Undefined"], "ans": get_ans(0)},
        {"que": "Are timers precise?", "options": ["No, minimum delay", "Yes, exact", "Depends", "Always late"], "ans": get_ans(0)},
        {"que": "What is minimum delay?", "options": ["4ms in browsers", "0ms", "1ms", "10ms"], "ans": get_ans(0)},
        {"que": "Can timers be nested?", "options": ["Yes", "No", "Only setTimeout", "Only setInterval"], "ans": get_ans(0)},
        {"que": "Why use timers?", "options": ["Defer execution", "Animate", "Poll", "All of above"], "ans": get_ans(3)}
    ],
    'assets/js_variables_quiz.json': [
        {"que": "What is var?", "options": ["Function-scoped variable", "Block-scoped", "Constant", "Global"], "ans": get_ans(0)},
        {"que": "What is let?", "options": ["Block-scoped variable", "Function-scoped", "Constant", "Global"], "ans": get_ans(0)},
        {"que": "What is const?", "options": ["Constant value", "Variable", "Function", "Object"], "ans": get_ans(0)},
        {"que": "What is hoisting?", "options": ["Declarations moved up", "Values moved up", "Code executed", "Variables deleted"], "ans": get_ans(0)},
        {"que": "What is temporal dead zone?", "options": ["Time before declaration", "After declaration", "During execution", "After execution"], "ans": get_ans(0)},
        {"que": "What is undefined?", "options": ["Unassigned value", "Null value", "Error", "Zero"], "ans": get_ans(0)},
        {"que": "What is null?", "options": ["Intentional absence", "Unassigned", "Error", "Empty string"], "ans": get_ans(0)},
        {"que": "What is scope?", "options": ["Variable visibility", "Code block", "Function", "File"], "ans": get_ans(0)},
        {"que": "What is global scope?", "options": ["Accessible everywhere", "Inside function", "Inside block", "Nowhere"], "ans": get_ans(0)},
        {"que": "What is local scope?", "options": ["Inside function/block", "Global", "Everywhere", "Nowhere"], "ans": get_ans(0)}
    ]
}

for path, questions in quizzes.items():
    dest = Path(path)
    with dest.open('w', encoding='utf-8') as f:
        json.dump(questions, f, indent=2)
print(f"Updated {len(quizzes)} JavaScript quiz files.")